config/routes.rb
Rails.application.routes.draw do
  post 'index/lexical_analyser', as: 'lexical'

  get '/syntactic' => 'syntacs#index', as: 'syntactic'
  get '/error' => 'syntacs#new', as: 'error'
  post '/syntacs/parsing', as: 'parsing'
  post '/syntacs/parsing_error', as: 'parsing_error'

  get '/translate' => 'translate_to_assembler#index', as: 'translate'
  post '/translate/assembler' => 'translate_to_assembler#translate', as: 'assembler'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'index#index'
end

app/views/index/index.html.erb
<h1>Компилятор модельного языка</h1>
<div class="row">
  <div class="col-sm-5">
    <%= form_tag lexical_path, class: 'lexical-form' do %>
        <p>Введите текст программы:</p>
        <%= text_area_tag 'program', nil, class: 'text-field' %>
        <%= button_tag 'Лексический анализ', class: 'btn btn-primary', remote: true %>
    <% end %>
  </div>
  <div class="col-sm-6 col-sm-offset-1">
    <div class="panel panel-success code">
      <div class="panel-heading" data-toggle="collapse" data-target="#collapseCode">
        Синтаксис языка
      </div>
      <div class="collapse panel-body" id="collapseCode">
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseProgram">
            Программа
          </div>
          <div class="collapse panel-body" id="collapseProgram">
            <pre>
  {
    /* Текст программы */
  }</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseDescription">
            Описание типов
          </div>
          <div class="collapse panel-body" id="collapseDescription">
            <pre>
  int &lt имя переменной &gt {, &lt имя переменной &gt} ;
  float &lt имя переменной &gt {, &lt имя переменной &gt} ;
  bool &lt имя переменной &gt {, &lt имя переменной &gt} ;</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseComposite">
            Описание составного оператора
          </div>
          <div class="collapse panel-body" id="collapseComposite">
            <pre>
  {
    &lt оператор &gt
    ...
    &lt оператор &gt
  }</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseAssigment">
            Описание оператора присваивания
          </div>
          <div class="collapse panel-body" id="collapseAssigment">
            <pre>
  &lt имя переменной &gt ass &lt выражение &gt ;</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseIf">
            Описание условного оператора
          </div>
          <div class="collapse panel-body" id="collapseIf">
            <pre>
if ( &lt сравнение &gt )
  &lt оператор &gt
{
  elseif ( &lt сравнение &gt )
    &lt оператор &gt
}
[
  else
    &lt оператор &gt
]
endif</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseWhile">
            Описание оператора условного цикла
          </div>
          <div class="collapse panel-body" id="collapseWhile">
            <pre>
while ( &lt сравнение &gt )
&lt оператор &gt</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseFor">
            Описание оператора фиксированного цикла
          </div>
          <div class="collapse panel-body" id="collapseFor">
            <pre>
for ( &lt присваивание &gt ; to &lt сравнение &gt ;
      [step &lt выражение &gt ;] )
&lt оператор &gt
next</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseRead">
            Описание оператора ввода
          </div>
          <div class="collapse panel-body" id="collapseRead">
            <pre>
read ( &lt имя переменной &gt {, &lt имя переменной &gt} );</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseWrite">
            Описание оператора вывода
          </div>
          <div class="collapse panel-body" id="collapseWrite">
            <pre>
write &lt выражение &gt {, &lt выражение &gt} ;</pre>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" data-toggle="collapse" data-target="#collapseComment">
            Описание комментария
          </div>
          <div class="collapse panel-body" id="collapseComment">
            <pre>
# Текст комментария</pre>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $(".lexical-form").validate({
      rules:{
        program:{
          required: true
        }
      },
      messages:{
        program:{
          required: "Поле обязательно для заполнения."
        }
      }
    });
  });
</script>