config/routes.rb
Rails.application.routes.draw do
  post 'index/lexical_analyser', as: 'lexical'

  get '/syntactic' => 'syntacs#index', as: 'syntactic'
  get '/error' => 'syntacs#new', as: 'error'
  post '/syntacs/parsing', as: 'parsing'
  post '/syntacs/parsing_error', as: 'parsing_error'

  get '/translate' => 'translate_to_assembler#index', as: 'translate'
  post '/translate/assembler' => 'translate_to_assembler#translate', as: 'assembler'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'index#index'
end

app/controllers/translate_to_assembler.rb
class TranslateToAssembler
  def initialize(options={})
    @program = options['program']
    @table = options['table']
    @position = 0
    @start_memory = 200
    @mark = 0
    @code = ''
  end

  def translate
    while @position < @program.size
      lexeme = read_lexeme
      if compare?({lexeme: lexeme, template: '{'}) || compare?({lexeme: lexeme, template: '}'}) ||
          compare?({lexeme: lexeme, template: 'int'}) || compare?({lexeme: lexeme, template: 'float'}) ||
          compare?({lexeme: lexeme, template: 'bool'}) || compare?({lexeme: lexeme, template: 'ass'}) ||
          compare?({lexeme: lexeme, template: 'next'}) || compare?({lexeme: lexeme, template: ';'})
        next
      end
      case_operator(get_word(lexeme))
    end
    @code += "HLT\n"
    @table['2'].pop
    { program: @program, table: @table, assembler: @code }
  end

  private

  def case_operator(word)
    case word
      when 'if'
        translate_if
      when 'for'
        translate_for
      when 'while'
        translate_while
      when 'read'
        translate_read
      when 'writeln'
        translate_write
      else
        translate_ass(word)
    end
  end

  def translate_composite # Перевод составного оператора
    lexeme = read_lexeme
    until compare?({lexeme: lexeme, template: '}'})
      case_operator(get_word(lexeme))
      lexeme = read_lexeme
    end
  end

  def translate_if # Перевод условного оператора
    state = 0
    next_mark = ''
    have_else = false
    while state != 3
      case state
      when 0
        translate = translate_comparison({end_comparison: ')'})
        next_mark = translate[:mark]
        @code += translate[:code]
        state += 1
      when 1
        lexeme = read_lexeme
        if compare?({lexeme: lexeme, template: '{'})
          translate_composite
          state += 1
          next
        end
        next if compare?({lexeme: lexeme, template: ')'})
        case_operator(get_word(lexeme))
        state += 1
      when 2
        lexeme = read_lexeme
        if compare?({lexeme: lexeme, template: 'elseif'})
          state = 0
          @code += "m#{next_mark}: "
          next
        end
        if compare?({lexeme: lexeme, template: 'else'})
          state = 1
          @code += "m#{next_mark}: "
          have_else = true
          next
        end
        if compare?({lexeme: lexeme, template: 'endif'})
          state += 1
          @code += "m#{next_mark}: " unless have_else
          next
        end
      end
    end
  end

  def translate_for # Перевод оператора фиксированного цикла
    state = 0
    begin_mark = exit_mark = temp_code = temp_identifier = ''
    while state != 5
      case state
        when 0
          read_lexeme
          temp_identifier = get_word(read_lexeme)
          translate_ass(temp_identifier)
          state += 1
        when 1
          @code += "m#{@mark}: "
          begin_mark = @mark
          @mark += 1
          read_lexeme
          translate = translate_comparison({end_comparison: ';'})
          exit_mark = translate[:mark]
          @code += translate[:code]
          state += 1
        when 2
          read_lexeme
          (compare?({lexeme: read_lexeme, template: 'step'})) ?
              temp_code = translate_expression({end_first: ')'}) :
              return_lexeme
          state += 1
        when 3
          lexeme = read_lexeme
          if compare?({lexeme: lexeme, template: '{'})
            translate_composite
            state += 1
            next
          end
          next if compare?({lexeme: lexeme, template: ')'})
          case_operator(get_word(lexeme))
          state += 1
        when 4
          unless temp_code.empty?
            @code += temp_code
            @code += "WR #{@start_memory + get_address(temp_identifier['name'])}\n"
          end
          @code += "JMP m#{begin_mark}\nm#{exit_mark}: "
          state += 1
      end
    end

  end

  def translate_while # Перевод оператора условного цикла
    state = 0
    exit_mark = ''
    @code += "m#{@mark}: "
    begin_mark = @mark
    @mark += 1
    while state != 3
      case state
      when 0
        translate = translate_comparison({end_comparison: ')'})
        exit_mark = translate[:mark]
        @code += translate[:code]
        state += 1
      when 1
        lexeme = read_lexeme
        if compare?({lexeme: lexeme, template: '{'})
          translate_composite
          state += 1
          next
        end
        next if compare?({lexeme: lexeme, template: ')'})
        case_operator(get_word(lexeme))
        state += 1
      when 2
        @code += "JMP m#{begin_mark}\nm#{exit_mark}: "
        state += 1
      end
    end
  end

  def translate_read # Перевод оператора ввода
    state = 0
    while state != 2
      lexeme = read_lexeme
      next if compare?({lexeme: lexeme, template: '('})
      case state
      when 0
        lexeme = get_word(lexeme)
        @code += "IN\nWR #{@start_memory + get_address(lexeme['name'])}\n"
        state += 1
      when 1
        if compare?({lexeme: lexeme, template: ','})
          state = 0
          next
        end
        state += 1
      end
    end
  end

  def translate_write # Перевод оператора вывода
    state = 0
    while state != 2
      case state
      when 0
        @code += translate_expression({end_first: ',', end_second: ';'})
        @code += "OUT\n"
        state += 1
      when 1
        if compare?({lexeme: read_lexeme, template: ','})
          state = 0
          next
        end
        state += 1
      end
    end
  end

  def translate_ass(identifier) # Перевод оператора присваивания
    id = false
    @table['2'].each do |elem|
      if elem == identifier
        id = true
        break
      end
    end
    return unless id
    state = 0
    while state != 2
      case state
      when 0
        (compare?({lexeme: read_lexeme, template: 'ass'})) ? state += 1 : return
      when 1
        @code += translate_expression({end_first: ';'})
        @code += "WR #{@start_memory + get_address(identifier['name'])}\n"
        state += 1
      end
    end
  end

  def translate_expression(options={}) # Перевод выражения
    expression = read_expression({end_first: options[:end_first], end_second: options[:end_second],
                                  end_third: options[:end_third], end_fourth: options[:end_fourth]})
    return if expression.empty?
    polisi = translate_to_postfix({expression: expression})
    code = ''
    temp_lexeme = []
    until polisi.empty?
      temp = polisi.shift
      case temp
      when '+'
        right = temp_lexeme.pop
        left = temp_lexeme.pop
        identifier?(left) ? code += "RD #{@start_memory + get_address(left)}\n" : code += "RD ##{left}\n"
        identifier?(right) ? code += "ADD #{@start_memory + get_address(right)}\n" : code += "ADD ##{right}\n"
        code += set_address(temp_lexeme)
        next
      when '-'
        right = temp_lexeme.pop
        left = temp_lexeme.pop
        identifier?(left) ? code += "RD #{@start_memory + get_address(left)}\n" : code += "RD ##{left}\n"
        identifier?(right) ? code += "SUB #{@start_memory + get_address(right)}\n" : code += "SUB ##{right}\n"
        code += set_address(temp_lexeme)
        next
      when '*'
        right = temp_lexeme.pop
        left = temp_lexeme.pop
        identifier?(left) ? code += "RD #{@start_memory + get_address(left)}\n" : code += "RD ##{left}\n"
        identifier?(right) ? code += "MUL #{@start_memory + get_address(right)}\n" : code += "MUL ##{right}\n"
        code += set_address(temp_lexeme)
        next
      when '/'
        right = temp_lexeme.pop
        left = temp_lexeme.pop
        identifier?(left) ? code += "RD #{@start_memory + get_address(left)}\n" : code += "RD ##{left}\n"
        identifier?(right) ? code += "DIV #{@start_memory + get_address(right)}\n" : code += "DIV ##{right}\n"
        code += set_address(temp_lexeme)
        next
      when '&&'
        right = temp_lexeme.pop
        left = temp_lexeme.pop
        if identifier?(left)
          code += "RD #{@start_memory + get_address(left)}\n"
        else
          (left == 'true') ? code += "RD #1\n" : code += "RD #0\n"
        end
        if identifier?(right)
          code += "AND #{@start_memory + get_address(right)}\n"
        else
          (right == 'true') ? code += "AND #1\n" : code += "AND #0\n"
        end
        code += set_address(temp_lexeme)
        next
      when '||'
        right = temp_lexeme.pop
        left = temp_lexeme.pop
        if identifier?(left)
          code += "RD #{@start_memory + get_address(left)}\n"
        else
          (left == 'true') ? code += "RD #1\n" : code += "RD #0\n"
        end
        if identifier?(right)
          code += "OR #{@start_memory + get_address(right)}\n"
        else
          (right == 'true') ? code += "OR #1\n" : code += "OR #0\n"
        end
        code += set_address(temp_lexeme)
        next
      when '!'
        lexeme = temp_lexeme.pop
        if identifier?(lexeme)
          code += "RD #{@start_memory + get_address(lexeme)}\n"
        else
          (lexeme == 'true') ? code += "RD #1\n" : code += "RD #0\n"
        end
        code += "NOT\n"
        code += set_address(temp_lexeme)
        next
      else
        temp_lexeme.push(temp)
      end
    end
    (0...@table['2'].size).map do |i|
      if @table['2'][i]['name'] =~ /M\d+/ && @table['2'][i]['name'] != 'M1'
        @table['2'].delete_at(i)
      end
    end
    temp_lexeme.each do |elem|
      unless elem =~ /M\d+/
        lexeme = temp_lexeme.pop
        identifier?(lexeme) ? code += "RD #{@start_memory + get_address(lexeme)}\n" : code += "RD ##{lexeme}\n"
        return code
      end
    end
    code[-1] = ''
    code[-1] = '' until code[-1] == "\n"
    code
  end

  def translate_to_postfix(options={}) # Перевод выражения в постфиксную форму записи
    result = []
    operation = []
    expression = options[:expression]

app/controllers/translate_to_assembler_controller.rb
class TranslateToAssemblerController < ApplicationController
  def index
    @json = Program.last
    @json = JSON.parse(@json[:json])
    if @json['assembler'].nil?
      @json['assembler'] = ''
    end
  end

  def translate
    @json = Program.last
    @json = JSON.parse(@json[:json])
    assembler = TranslateToAssembler.new(@json)
    @json = @json.merge(assembler.translate)
    text = Program.new({json: @json.to_json})
    text.save
    redirect_to :back
  end
end

app/helpers/translate_to_assembler_helper.rb
module TranslateToAssemblerHelper
end

app/views/translate_to_assembler/index.html.erb
<h1>Компилятор модельного языка</h1>
<div class="row">
  <div class="col-sm-5">
    <%= form_tag assembler_path do %>
        <p>Текст программы:</p>
        <%= text_area_tag 'text', @json['text'], class: 'code-field', disabled: true %>
        <%= button_tag 'Трансляция в Assembler', class: 'btn btn-primary analyse', remote: true %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <p>Текст программы списком лексем:</p>
    <%= text_area_tag 'program', @json['program'], class: 'code-field', disabled: true %>
    <%= link_to 'Внести изменения в текст программы', error_path, class: 'btn btn-warning trigger' %>
  </div>
  <div class="col-sm-3">
    <p>Текст программы на языке Assembler</p>
    <%= text_area_tag 'assembler', @json['assembler'], class: 'code-field', disabled: true %>
    <%= link_to 'Ввести новый текст программы', root_path, class: 'btn btn-danger trigger' %>
  </div>
</div>
<div class="row">
  <div class="panel panel-success show-table">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseTable">
      Таблицы символов
    </div>
    <div class="collapse panel-body" id="collapseTable">
      <div class="row">
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseKeyword">
              Таблица ключевых слов
            </div>
            <div class="collapse panel-body" id="collapseKeyword">
              <table class="table table-bordered">
                <% @json['table']['0'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['0'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseDelimiter">
              Таблица разделителей
            </div>
            <div class="collapse panel-body" id="collapseDelimiter">
              <table class="table table-bordered">
                <% @json['table']['1'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['1'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseIdentifier">
              Таблица идентификаторов
            </div>
            <div class="collapse panel-body" id="collapseIdentifier">
              <table class="table table-bordered">
                <% @json['table']['2'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['2'][i]['name'] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseConstant">
              Таблица констант
            </div>
            <div class="collapse panel-body" id="collapseConstant">
              <table class="table table-bordered">
                <% @json['table']['3'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['3'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="success-message">
  <div class="panel panel-success">
    <div class="panel-heading">Выполнено!</div>
    <div class="panel-body">
      <% if @json['assembler'].empty? %>
        <p>
          В результате синтаксического и семантического анализа ошибок не обнаружено.
        </p>
      <% else %>
        <p>
          Трансляция в Assembler успешно завершена.
        </p>
      <% end %>
      <button class="btn btn-success hide-popup">Закрыть</button>
    </div>
  </div>
</div>
<div class="modal-overlay"></div>

<script>
    var popup = $(".success-message");
    var overlay = $(".modal-overlay");
    $(".hide-popup").click(function (event) {
        event.preventDefault();
        overlay.css("display", "none");
        popup.css("display", "none");
    });
</script>