config/routes.rb
Rails.application.routes.draw do
  post 'index/lexical_analyser', as: 'lexical'

  get '/syntactic' => 'syntacs#index', as: 'syntactic'
  get '/error' => 'syntacs#new', as: 'error'
  post '/syntacs/parsing', as: 'parsing'
  post '/syntacs/parsing_error', as: 'parsing_error'

  get '/translate' => 'translate_to_assembler#index', as: 'translate'
  post '/translate/assembler' => 'translate_to_assembler#translate', as: 'assembler'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'index#index'
end

app/controllers/syntacs_controller.rb
class SyntacsController < ApplicationController
  def index
    @json = Program.last
    @json = JSON.parse(@json[:json])
  end

  def new
    @json = Program.last
    @json = JSON.parse(@json[:json])
    @error = File.open(File.join(Rails.root, '/error.txt'), 'r') do |file|
      file.read
    end
    @error = @error.split("\n")
  end

  def parsing
    text = Program.last
    @json = JSON.parse(text[:json])
    parse = Parsing.new(@json)
    @json = @json.update(parse.analyse)
    text = Program.new({json: @json.to_json})
    text.save
    @error = File.open(File.join(Rails.root, '/error.txt'), 'r') do |file|
      file.read
    end
    if @error.empty?
      redirect_to translate_path
    else
      redirect_to error_path
    end
  end

  def parsing_error
    lexical_result = { text: params[:program] }
    lexical_analysis = LexicalAnalyser.new(lexical_result[:text])
    lexical_result = lexical_result.update(lexical_analysis.analyse)
    text = Program.new({json: lexical_result.to_json})
    text.save
    parsing
  end
end

app/helpers/syntacs_helper.rb
module SyntacsHelper
end

app/views/syntacs/index.html.erb
<h1>Компилятор модельного языка</h1>
<div class="row">
  <div class="col-sm-5">
    <%= form_tag parsing_path do %>
        <p>Текст программы:</p>
        <%= text_area_tag 'program', @json['text'], class: 'code-field', disabled: true %>
        <%= button_tag 'Синтаксический анализ', class: 'analyse btn btn-primary', remote: true %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <p>Текст программы списком лексем:</p>
    <%= text_area_tag 'program', @json['program'], class: 'code-field', disabled: true %>
  </div>
</div>
<div class="row">
  <div class="panel panel-success show-table">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseTable">
      Таблицы символов
    </div>
    <div class="collapse panel-body" id="collapseTable">
      <div class="row">
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseKeyword">
              Таблица ключевых слов
            </div>
            <div class="collapse panel-body" id="collapseKeyword">
              <table class="table table-bordered">
                <% @json['table']['0'].each_index do |i| %>
                  <tr>
                    <th>[<%= i + 1 %>]</th>
                    <td><%= @json['table']['0'][i] %></td>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseDelimiter">
              Таблица разделителей
            </div>
            <div class="collapse panel-body" id="collapseDelimiter">
              <table class="table table-bordered">
                <% @json['table']['1'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['1'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseIdentifier">
              Таблица идентификаторов
            </div>
            <div class="collapse panel-body" id="collapseIdentifier">
              <table class="table table-bordered">
                <% @json['table']['2'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['2'][i]['name'] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseConstant">
              Таблица констант
            </div>
            <div class="collapse panel-body" id="collapseConstant">
              <table class="table table-bordered">
                <% @json['table']['3'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['3'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/syntacs/new.html.erb
<h1>Компилятор модельного языка</h1>
<div class="row">
  <div class="col-sm-5">
    <%= form_tag parsing_error_path, class: 'lexical-form' do %>
        <p>Текст программы:</p>
        <%= text_area_tag 'program', @json['text'], class: 'code-field' %>
        <%= button_tag 'Синтаксический анализ', class: 'btn btn-primary analyse', remote: true %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <p>Текст программы списком лексем:</p>
    <%= text_area_tag 'program', @json['program'], class: 'code-field', disabled: true %>
  </div>
</div>
<% unless @error.empty? %>
  <div class="row">
    <div class="panel panel-danger show-table">
      <div class="panel-heading" data-toggle="collapse" data-target="#collapseError">
        Список ошибок
      </div>
      <div class="collapse panel-body" id="collapseError">
        <% @error.each do |elem| %>
          <p><%= elem %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="panel panel-success show-table">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseTable">
      Таблицы символов
    </div>
    <div class="collapse panel-body" id="collapseTable">
      <div class="row">
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseKeyword">
              Таблица ключевых слов
            </div>
            <div class="collapse panel-body" id="collapseKeyword">
              <table class="table table-bordered">
                <% @json['table']['0'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['0'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseDelimiter">
              Таблица разделителей
            </div>
            <div class="collapse panel-body" id="collapseDelimiter">
              <table class="table table-bordered">
                <% @json['table']['1'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['1'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseIdentifier">
              Таблица идентификаторов
            </div>
            <div class="collapse panel-body" id="collapseIdentifier">
              <table class="table table-bordered">
                <% @json['table']['2'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['2'][i]['name'] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="panel panel-success">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapseConstant">
              Таблица констант
            </div>
            <div class="collapse panel-body" id="collapseConstant">
              <table class="table table-bordered">
                <% @json['table']['3'].each_index do |i| %>
                    <tr>
                      <th>[<%= i + 1 %>]</th>
                      <td><%= @json['table']['3'][i] %></td>
                    </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% unless @error.empty? %>
  <div class="error-message">
    <div class="panel panel-danger">
      <div class="panel-heading">Внимание!</div>
      <div class="panel-body">
        <p>
          В тексте программы обнаружены ошибки: <strong><%= @error.size %></strong>.
        </p>
        <p>Ошибки перечислены во вкладке "Список ошибок".</p>
        <button class="btn btn-danger hide-popup">Закрыть</button>
      </div>
    </div>
  </div>
  <div class="modal-overlay"></div>
<% end %>

<script>
  var popup = $(".error-message");
  var overlay = $(".modal-overlay");
  $(".hide-popup").click(function (event) {
      event.preventDefault();
      overlay.css("display", "none");
      popup.css("display", "none");
  })
  $(document).ready(function(){
      $(".lexical-form").validate({
          rules:{
              program:{
                  required: true
              }
          },
          messages:{
              program:{
                  required: "Поле обязательно для заполнения."
              }
          }
      });
  });
</script>